--Create Database
CREATE DATABASE EVENT_MANAGER;

--CONSTANT TABLES - DATA OF AVAILABLE SERVICES
CREATE TABLE EVENT_TYPES (EVENT_TYPEID INT(4) PRIMARY KEY, EVENT_TYPE VARCHAR(64), EVENT_TYPE_DESCRIPTION VARCHAR(1024), BASE_COST INT(8));
CREATE TABLE LOCATIONS (LOCATION_ID INT(4) PRIMARY KEY, LOCATION_TYPE VARCHAR(32), LOCATION_NAME VARCHAR(128), LOCATION_ADDRESS VARCHAR(1024));
CREATE TABLE ADD_ONS (ADDON_TYPEID INT(4) PRIMARY KEY, ADDON_TYPE VARCHAR(64), ADDON_SUBTYPE VARCHAR(64), ADDON_DESCRIPTION VARCHAR(1024), ADDON_COST INT(8));

--USER DEFINED TABLES - INFORMATIONS ABOUT THE USER AND THEIR EVENTS
CREATE TABLE USER_INFORMATION (USER_ID INT(8) PRIMARY KEY NOT NULL auto_incremenT, FIRST_NAME VARCHAR(64), LAST_NAME VARCHAR(64), EMAIL_ID VARCHAR(128), USER_ADDRESS VARCHAR (1024), CONTACT_NUMBER CHAR(16), EVENT_COUNT INT(8) DEFAULT 0, CREATED_DATE DATETIME default current_timestamp, UPDATED_DATE DATETIME default current_timestamp)auto_increment=10001;
CREATE TABLE USER_REGISTRY (USER_ID INT(8) PRIMARY KEY NOT NULL , USER_NAME VARCHAR(128), PASSWORD CHAR(64), CREATED_DATE DATETIME default current_timestamp, UPDATED_DATE DATETIME default current_timestamp);
CREATE TABLE EVENT_INFORMATION (EVENT_ID INT(8) PRIMARY KEY NOT NULL auto_incremenT, USER_ID INT(8), EVENT_TYPEID INT(4), EVENT_NAME VARCHAR(128), START_DATE DATETIME, END_DATE DATETIME , LOCATION_ID INT(4), ATTENDEE_COUNT INT(8), ADD_ONS INT(1), ESTIMATED_COST INT(10), EVENT_DESCRIPTION VARCHAR(1024), EVENT_STATUS INT(1), REGISTER_TIME DATETIME default current_timestamp) auto_increment=1001;
CREATE TABLE EVENT_ADDONS_INFORMATION (EVENT_ID INT(4) , ADDON_1 INT(4), ADDON1_COUNT INT(8), ADDON_2 INT(4), ADDON2_COUNT INT(8), ADDON_3 INT(1) , ADDON3_COUNT INT(8), TOTAL_ADDON_COST INT(8));

--DATA ENTRY INTO TABLE - EVENT_TYPES
INSERT INTO EVENT_MANAGER.EVENT_TYPES VALUES(101, 'Birthday', '', 1720);
INSERT INTO EVENT_MANAGER.EVENT_TYPES VALUES(102, 'Wedding Anniversary', '', 5000);
INSERT INTO EVENT_MANAGER.EVENT_TYPES VALUES(103, 'Wedding', '', 15000);
INSERT INTO EVENT_MANAGER.EVENT_TYPES VALUES(104, 'Get-together', '', 5000);
INSERT INTO EVENT_MANAGER.EVENT_TYPES VALUES(105, 'Alumini-Meet', '', 1720);
INSERT INTO EVENT_MANAGER.EVENT_TYPES VALUES(106, 'Upanayanam', '', 10000);
INSERT INTO EVENT_MANAGER.EVENT_TYPES VALUES(107, 'Stand-up Comedy Show', '', 1720);
INSERT INTO EVENT_MANAGER.EVENT_TYPES VALUES(108, 'Musical Concert', '', 5000);




--DATA ENTRY INTO TABLE - LOCATIONS
INSERT INTO EVENT_MANAGER.LOCATIONS VALUES(101, 'Restaurent', '<name>', 'Dummy');
INSERT INTO EVENT_MANAGER.LOCATIONS VALUES(102, 'Hotel', '<name>', 'Dummy');
INSERT INTO EVENT_MANAGER.LOCATIONS VALUES(103, 'Academic Venue', '<name>', 'Dummy');
INSERT INTO EVENT_MANAGER.LOCATIONS VALUES(104, 'Art Gallary', '<name>', 'Dummy');
INSERT INTO EVENT_MANAGER.LOCATIONS VALUES(105, 'Conference Centres', '<name>', 'Dummy');
INSERT INTO EVENT_MANAGER.LOCATIONS VALUES(106, 'Parks/Fields', '<name>', 'Dummy');
INSERT INTO EVENT_MANAGER.LOCATIONS VALUES(107, 'Auditoruim', '<name>', 'Dummy');


--DATA ENTRY INTO TABLE - ADD_ONS
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(101, 'Food', 'Tiffen', '', 60);
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(102, 'Food', 'Minimeal', '', 150);
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(103, 'Food', 'Lunch', '', 172 );
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(104, 'Food', 'Dinner', '', 250 );
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(105, 'Food', 'One-Day Meal', '', 500 );
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(106, 'Food', 'Tiffen & Lunch', '', 250 );
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(107, 'Food', 'Lunch & Dinner', '', 400 );
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(201, 'Invitation', 'Theme1', '', 50 );
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(202, 'Invitation', 'Theme2', '', 60 );
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(203, 'Invitation', 'Theme3', '', 70 );
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(204, 'Invitation', 'Theme4', '', 60 );
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(301, 'Decoration', 'Classic', '', 1500 );
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(302, 'Decoration', 'Western', '', 1720 );
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(303, 'Decoration', 'Traditional', '', 1720 );
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(304, 'Decoration', 'Kids', '', 1000 );
INSERT INTO EVENT_MANAGER.ADD_ONS VALUES(305, 'Decoration', 'Minimalist', '', 1000 );