/*
-- Query: select * from EVENT_TYPES
LIMIT 0, 1000

-- Date: 2022-10-28 07:57
*/
INSERT INTO `` (`EVENT_TYPEID`,`EVENT_TYPE`,`EVENT_TYPE_DESCRIPTION`,`BASE_COST`) VALUES (101,'Birthday','',1720);
INSERT INTO `` (`EVENT_TYPEID`,`EVENT_TYPE`,`EVENT_TYPE_DESCRIPTION`,`BASE_COST`) VALUES (102,'Wedding Anniversary','',5000);
INSERT INTO `` (`EVENT_TYPEID`,`EVENT_TYPE`,`EVENT_TYPE_DESCRIPTION`,`BASE_COST`) VALUES (103,'Wedding','',15000);
INSERT INTO `` (`EVENT_TYPEID`,`EVENT_TYPE`,`EVENT_TYPE_DESCRIPTION`,`BASE_COST`) VALUES (104,'Get-together','',5000);
INSERT INTO `` (`EVENT_TYPEID`,`EVENT_TYPE`,`EVENT_TYPE_DESCRIPTION`,`BASE_COST`) VALUES (105,'Alumini-Meet','',1720);
INSERT INTO `` (`EVENT_TYPEID`,`EVENT_TYPE`,`EVENT_TYPE_DESCRIPTION`,`BASE_COST`) VALUES (106,'Upanayanam','',10000);
INSERT INTO `` (`EVENT_TYPEID`,`EVENT_TYPE`,`EVENT_TYPE_DESCRIPTION`,`BASE_COST`) VALUES (107,'Stand-up Comedy Show','',1720);
INSERT INTO `` (`EVENT_TYPEID`,`EVENT_TYPE`,`EVENT_TYPE_DESCRIPTION`,`BASE_COST`) VALUES (108,'Musical Concert','',5000);
